---
- name: Patching Playbook
  hosts: all
  become: true
  tasks:
    - name: Applying all the available patches
      dnf:
        name: "*"
        state: latest
      notify:
        - reboot_servers

  handlers:
    - name: reboot_servers
      reboot:
        reboot_timeout: 300
        test_command: uptime

