---
- name: install run and enable {{ something }}
  hosts: rhel
  tasks:
    - name: install {{ something }}
      package:
        name: "{{ something }}"
        state: latest

    - name: run and enable {{ something }}
      service:
        name: "{{ something }}"
        state: started
        enabled: true
