---
- name: remove {{ something }}
  hosts: rhel
  tasks:
    - name: stop {{ something }}
      service:
        name: "{{ something }}"
        enabled: false
        state: stopped

    - name: uninstall {{ something }}
      package:
        name: "{{ something }}"
        state: absent
